os:
  - linux
language: node_js
node_js:
  - v9
  - v8
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - yarn global add yo
install:
  - yarn install
script:
  - yarn run test
